"""
schemas.py

Pydantic schemas — the contract layer of the API.

Pydantic is a Python library that validates data automatically.
You define a class with typed fields and Pydantic checks that
any incoming data matches those types before your endpoint
function even runs.

Think of schemas as the form that callers must fill in correctly.
If they leave out a required field or put the wrong type in a field,
Pydantic rejects the request with a clear 422 error before
any of your code runs.

Two categories of schemas live here:
    Request schemas  — what callers must SEND to each endpoint
    Response schemas — what callers will RECEIVE from each endpoint
"""

from typing import Optional
from datetime import datetime
from pydantic import BaseModel, Field
# BaseModel is the parent class all Pydantic schemas inherit from.
# Field() lets you add extra information to a field — like a
# description that shows up in the Swagger docs, or a default value,
# or validation rules like minimum length.


# ─────────────────────────────────────────────────────────────
# REQUEST SCHEMAS — what callers send IN
# ─────────────────────────────────────────────────────────────

class RunRequest(BaseModel):
    """
    What a caller must send to POST /run.

    This is the main request schema — the most important one.
    Every field here maps directly to what llm_runner.run_prompt() needs.
    """

    prompt: Optional[str] = Field(
        default=None,
        description="The text prompt to send to all models.",
        example="In one sentence, what is machine learning?"
    )

    models: Optional[list[str]] = Field(
        default=None,
        description="Which models to run. If not provided, runs all 3.",
        example=["gpt-4o-mini", "llama-groq", "gemini-flash"]
    )
    # Optional means the caller can leave this out.
    # If they do not send it, it defaults to None.
    # main.py then passes None to run_prompt() which uses DEFAULT_MODELS.

    model_conversations: Optional[dict[str, list[dict]]] = Field(
        default=None,
        description=(
            "Per-model full conversation history for multi-turn runs. "
            "Key = model name, Value = list of {role, content} messages "
            "including the new user message at the end. "
            "When provided, each model receives its own history so responses stay in context."
        ),
    )

    temperature: Optional[float] = Field(
        default=0.7,
        ge=0.0,
        le=2.0,
        description="Sampling temperature for all models. 0.0 = deterministic, 2.0 = very creative. Default 0.7.",
        example=0.7,
    )

    session_id: Optional[str] = Field(
        default=None,
        description="Session ID that groups all /run calls from one chat together. Generated by the client.",
    )

    system_prompt: Optional[str] = Field(
        default=None,
        description="System prompt prepended to every model call. Sets persona or constraints.",
    )


# ─────────────────────────────────────────────────────────────
# RESPONSE SCHEMAS — what callers receive back
# ─────────────────────────────────────────────────────────────

class ModelResultResponse(BaseModel):
    """
    The result from one model for one run.

    This mirrors the ModelResult dataclass in llm_runner.py
    but as a Pydantic model so FastAPI can serialize it to JSON
    and document it in Swagger automatically.

    One RunResponse contains a list of these — one per model.
    """

    model: str = Field(
        description="The friendly model name.",
        example="gpt-4o-mini"
    )

    response: Optional[str] = Field(
        description="The text the model returned. None if the call failed.",
        example="Machine learning is the process of teaching computers..."
    )

    latency_ms: int = Field(
        description="How long this model took to respond in milliseconds.",
        example=847
    )

    input_tokens: int = Field(
        description="Number of tokens in the prompt we sent.",
        example=12
    )

    output_tokens: int = Field(
        description="Number of tokens in the response we received.",
        example=18
    )

    total_tokens: int = Field(
        description="input_tokens + output_tokens",
        example=30
    )

    cost_usd: float = Field(
        description="Estimated cost of this call in US dollars.",
        example=0.000079
    )

    success: bool = Field(
        description="True if the model responded successfully.",
        example=True
    )

    error: Optional[str] = Field(
        description="None if success. Error message if failed.",
        example=None
    )


class RunResponse(BaseModel):
    """
    The complete response from POST /run.

    Contains every model's result plus metadata about the whole run.
    This is what the Streamlit UI in Week 3 will receive and display.
    """

    run_id: str = Field(
        description="Unique ID for this run. Use with GET /runs/{run_id}.",
        example="a3f2c891-bd47-4f2a-9c12-e8f2d3b1c4a7"
    )

    prompt: str = Field(
        description="The original prompt that was sent to all models.",
        example="In one sentence, what is machine learning?"
    )

    results: list[ModelResultResponse] = Field(
        description="One result per model. Always in order: GPT, Llama, Gemini."
    )

    total_wall_clock_ms: int = Field(
        description="Total time for the entire run in milliseconds. "
                    "Because models run simultaneously this is close to "
                    "the slowest model, not the sum of all three.",
        example=923
    )

    models_succeeded: int = Field(
        description="How many models returned a successful response.",
        example=3
    )

    models_failed: int = Field(
        description="How many models failed (auth error, rate limit, etc).",
        example=0
    )

    system_prompt: Optional[str] = Field(
        default=None,
        description="The system prompt that was active for this run. None if not set.",
    )


class SessionSummary(BaseModel):
    """One row in the GET /sessions paginated list."""

    session_id: str
    first_prompt: str
    turn_count: int
    created_at: datetime


class SessionListResponse(BaseModel):
    """Paginated response for GET /sessions."""

    page: int
    page_size: int
    total_sessions: int
    total_pages: int
    sessions: list[SessionSummary]


class TurnResult(BaseModel):
    """One model's result within a session turn."""

    model: str
    response: Optional[str]
    latency_ms: int
    total_tokens: int
    cost_usd: float
    success: bool
    error: Optional[str]


class SessionTurn(BaseModel):
    """One user prompt + all model responses within a session."""

    run_id: str
    prompt: str
    system_prompt: Optional[str]
    created_at: datetime
    results: list[TurnResult]


class SessionDetailResponse(BaseModel):
    """Full conversation for GET /sessions/{session_id}."""

    session_id: str
    turns: list[SessionTurn]


class DeleteSessionsRequest(BaseModel):
    """Body for DELETE /sessions."""

    session_ids: list[str]


class DeleteSessionsResponse(BaseModel):
    """Result of DELETE /sessions."""

    deleted_count: int
    session_ids: list[str]